version: '3'
services:  
  hub:
    image: selenium/hub
    ports:
    - "4445:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300

  chrome1:
    image: selenium/node-chrome-debug
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports: 
      - "9001:5900"
    links:
      - hub
  chrome2:
    image: selenium/node-chrome-debug
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - /dev/shm:/dev/shm
    ports: 
      - "9002:5900"
    links:
      - hub
  firefox1:
    image: selenium/node-firefox-debug
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 6
      NODE_MAX_INSTANCES: 6
    volumes:
      - /dev/shm:/dev/shm
    ports: 
      - "9003:5900"
    links:
      - hub